name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-4x
  - conda-forge
dependencies:
  - xeus-r
  - xeus
  - r-colorspace
  - r-rcolorbrewer
  - r-htmltools
  - r-farver
  - r-dplyr
